trigger:
  batch: true
  branches:
    include:
      - cccs-main

variables:
  containerRegistry: uchimera
  baseImageRepository: acryldata/datahub-ingestion-base
  finalImageRepository: cccs/datahub-ingestion
  buildTimestamp: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]
  DOCKER_BUILDKIT: 1

pool:
  vmImage: ubuntu-latest

steps:
  - bash: |
      BRANCH_NAME=$(echo "$SYSTEM_PULLREQUEST_SOURCEBRANCH $BUILD_SOURCEBRANCH" | sed -r 's/^\s*(refs\/heads\/)?(\S*).*$/\2/' | sed 's/\//_/g')
      echo "##vso[task.setvariable variable=BRANCH_NAME]$BRANCH_NAME"
    displayName: Parse Source Control Branch Name
  - task: Docker@2
    displayName: Build base image
    inputs:
      command: build
      containerRegistry: $(containerRegistry)
      repository: $(baseImageRepository)
      dockerfile: $(Build.SourcesDirectory)/docker/datahub-ingestion-base/Dockerfile
      buildContext: $(Build.SourcesDirectory)
  - task: Docker@2
    displayName: Login to ${{ variables.containerRegistry }}
    inputs:
      command: login
      containerRegistry: ${{ variables.containerRegistry }}
  - task: Docker@2
    displayName: Build and Push DataHub Ingestion image
    inputs:
      command: buildAndPush
      containerRegistry: $(containerRegistry)
      repository: $(finalImageRepository)
      dockerfile: $(Build.SourcesDirectory)/docker/datahub-ingestion/Dockerfile
      buildContext: $(Build.SourcesDirectory)
      tags: |
        $(BRANCH_NAME)
        $(BRANCH_NAME)_$(buildTimestamp)_b$(Build.BuildId)
  - task: Docker@2
    displayName: Logout of ${{ variables.containerRegistry }}
    inputs:
      command: logout
      containerRegistry: ${{ variables.containerRegistry }}
    condition: always()
