trigger:
  batch: true
  branches:
    include:
      - cccs-main

variables:
  azureSubscriptionEndpoint: azure-uchimera
  azureContainerRegistry: uchimera.azurecr.io
  projectName: datahub
  gmsImageRepository: cccs/datahub-gms
  frontendImageRepository: cccs/datahub-frontend-react
  buildTimestamp: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]
  GRADLE_OPTS: -Xmx8g
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DATAHUB_GMS_IMAGE: cccs/datahub-gms
  DATAHUB_FRONTEND_IMAGE: cccs/datahub-frontend-react

pool:
  vmImage: ubuntu-latest

steps:
  - bash: |
      BRANCH_NAME=$(echo "$SYSTEM_PULLREQUEST_SOURCEBRANCH $BUILD_SOURCEBRANCH" | sed -r 's/^\s*(refs\/heads\/)?(\S*).*$/\2/' | sed 's/\//_/g')
      echo "##vso[task.setvariable variable=BRANCH_NAME]$BRANCH_NAME"
    displayName: Parse Source Control Branch Name
  - bash: |
      ./gradlew :metadata-service:war:build -x test --parallel
      cp ./metadata-service/war/build/libs/war.war .
    displayName: Build Datahub's backend GMS
  - bash: |
      ./gradlew :datahub-frontend:dist -PuseSystemNode=${USE_SYSTEM_NODE} -x test -x yarnTest -x yarnLint --parallel
      cp ./datahub-frontend/build/distributions/datahub-frontend-*.zip datahub-frontend.zip
    displayName: Build Datahub's frontend
  - task: DockerCompose@0
    displayName: Docker Compose Build
    inputs:
      action: Build services
      azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      azureContainerRegistry: $(azureContainerRegistry)
      dockerComposeFile: $(Build.SourcesDirectory)/docker/docker-compose.yml
      additionalDockerComposeFiles: |
        $(Build.SourcesDirectory)/docker/docker-compose.override.yml
      projectName: $(Build.Repository.Name)
      qualifyImageNames: true
      additionalImageTags: |
          $(BRANCH_NAME)
          $(BRANCH_NAME)_$(buildTimestamp)_b$(Build.BuildId)
  - task: DockerCompose@0
    displayName: Push images
    inputs:
      action: Push services
      azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      azureContainerRegistry: $(azureContainerRegistry)
      dockerComposeFile: $(Build.SourcesDirectory)/docker/docker-compose.yml
      additionalDockerComposeFiles: |
        $(Build.SourcesDirectory)/docker/docker-compose.override.yml
      projectName: $(Build.Repository.Name)
      qualifyImageNames: true
      additionalImageTags: |
          $(BRANCH_NAME)
          $(BRANCH_NAME)_$(buildTimestamp)_b$(Build.BuildId)
